### ISSUE TITLE
[BUG] Remove the Paypal option from the `FUNDING.yml`

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/LinkFree-CLI#12]
### Description

The line to remove:

```diff
- custom: [paypal.me/pradumnasaraf]
```

Path to the file:

https://github.com/Pradumnasaraf/LinkFree-CLI/blob/main/.github/FUNDING.yml

If you need any help feel free to drop a message below

**Comment by ritesh-karankal** [comment]
Hey Pradumna!, can I be assigned to this?

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by Pradumnasaraf** [comment]
> Hey Pradumna!, can I be assigned to this?

Yes, go ahead, Ritesh. Thank you!
