### ISSUE TITLE
Remove unwanted keys

### ISSUE THREAD

**Issue by Ananya2001-an** [Pradumnasaraf/LinkFree-CLI#15]
### Description

We no longer need the avatar and displayStatsPublic keys for creating LinkFree profile. We have to remove it from the createUser.js and questions.js util files. I would like to work on this.

**Comment by Vijeth56** [comment]
I am writing to request that I be assigned to work on Issue #15 in your repository.
I would greatly appreciate it if you could assign me to this issue so that I can get started on it as soon as possible.

**Comment by Ananya2001-an** [comment]
Hey @Pradumnasaraf you can assign it to @Vijeth56

**Comment by Pradumnasaraf** [comment]
Hey, @Ananya2001-

You can go ahead as you requested for it 1st.

**Comment by Pradumnasaraf** [comment]
Hey, @Vijeth56 you can look for some other open issues.
