### ISSUE TITLE
[FEATURE] Allowing only some changes when overwriting

### ISSUE THREAD

**Issue by Ananya2001-an** [Pradumnasaraf/LinkFree-CLI#16]
### Description

Currently when the users are allowed to overwrite their profile we are asking them to write everything from scratch. How about also asking them if they want to keep that field as it is? If not then they can overwrite or add anything they want to.

**Comment by Pradumnasaraf** [comment]
Thanks for opening the issue. Great point. We need to refactor the CLI soon there.

Currently locking this issue to 1st work on the reaming feature for new profile creation.

**Comment by Ananya2001-an** [comment]
Shall we close this issue now since we are going to merge the changes soon?

**Comment by Ananya2001-an** [comment]
Cool

**Comment by saaagarsingh** [comment]
So the issue has been closed right?

**Comment by Ananya2001-an** [comment]
> So the issue has been closed right?
> 

Hey @saaagarsingh We are actually prepping up for the release of v2.0.0 of LinkFree cli in which this issue has been resolved already. Once the changes are merged into main this issue will get closed automatically.
