### ISSUE TITLE
[BUG] Add a name to greetings workflow - `greetings.yml`

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/LinkFree-CLI#19]
### Description

Just above the `on:` property, add a `name:` property.

I should look like this

```yaml
name: Greetings

on:
```

File path - https://github.com/Pradumnasaraf/LinkFree-CLI/blob/main/.github/workflows/greetings.yml

**Comment by xanirudh** [comment]
Hello! Please assign this issue to me. thanks!

**Comment by Shipkush** [comment]
if this issue available.....please assign to me.

**Comment by Pradumnasaraf** [comment]
Hey, @xanirudh. Due to lots of notifications, I didn't see your comment on the issue, you commented 1st, and I merged the PR of a different contributor. Please look for another issue. Sorry for that mistake.
