### ISSUE TITLE
[BUG] Fix update profile message

### ISSUE THREAD

**Issue by Ananya2001-an** [Pradumnasaraf/LinkFree-CLI#42]
### Description

**Problem**
Right now when we make any updates to the JSON profile it gives us a message saying "*.json file updated successfully" but the same thing is also printed when no updates are made. 

**Potential solution**
A message like "No updates were made" should be printed instead.  

### Screenshots

![Screenshot 2023-02-24 183645](https://user-images.githubusercontent.com/55504616/221186513-d02951a7-26c5-489e-b8a2-89fd447d0779.jpg)

**Comment by yeshwantthota** [comment]
can I work on this issue?

**Comment by yeshwantthota** [comment]
Hey, I have a little doubt, I am making changes in the code base, but I cannot see that in my local linkfree cli, so please can anyone guide me, I am new to this type of project.

**Comment by Ananya2001-an** [comment]
> Hey, I have a little doubt, I am making changes in the code base, but I cannot see that in my local linkfree cli, so please can anyone guide me, I am new to this type of project.

That's weird. Can you explain a bit more clearly as to what changes you made ?

**Comment by yeshwantthota** [comment]
> Are you getting some error with data folder. Actually to test anything you will have to create a data folder in the root directory.

Thank you, got it 👍👍😊

**Comment by Ananya2001-an** [comment]
> > Are you getting some error with data folder. Actually to test anything you will have to create a data folder in the root directory.
> 
> Thank you, got it 👍👍😊

Awesome.
