### ISSUE TITLE
[FEATURE] Search filter for icons

### ISSUE THREAD

**Issue by Ananya2001-an** [Pradumnasaraf/LinkFree-CLI#43]
### Description

**Problem**
When selecting icons for adding to the link or milestones we have to scroll through this entire list which is quite cumbersome. 

**Potential solution**
It would be great if we can take input from user and create a search filter instead. This will reduce time to search for the desired icon. They can just type in the name of the icon and matched icons will show up to select from.

### Screenshots

![Screenshot 2023-02-24 184618](https://user-images.githubusercontent.com/55504616/221188686-78cb9bf1-b5af-410d-a2ce-ddc395577343.jpg)

**Comment by PratikDey** [comment]
Hi, I would like to contribute to this feature. Please, let me know how should I approach this.

**Comment by Ananya2001-an** [comment]
Thanks for showing interest in the issue @PratikDey. We would like to have something like below. You can refer to this link on how to implement it: https://github.com/enquirer/enquirer#autocomplete-prompt
![autocomplete-prompt](https://user-images.githubusercontent.com/55504616/221397154-0e69f4db-9394-453e-9c8e-eb0c2fd2c11a.gif)

**Comment by Ananya2001-an** [comment]
Hey @PratikDey Shall I assign this issue to you?

**Comment by PratikDey** [comment]
While running the project I am getting this error - 
```√ Choose one option (Press down arrow to traverse the list) · Update an existing JSON file
√ What is your GitHub username? (case sensitive) · pratikdey
√ Do you want to change your name? (y/N) · false
√ Do you want to change your profile type? (y/N) · false
√ Do you want to change your bio? (y/N) · false
√ Do you want to update your tags? (y/N) · false
√ Do you want to update your socials? (y/N) · true
√ What you want to do? · add a social?
AxiosError: connect ETIMEDOUT 2405:200:1607:2820:41::36:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  port: 443,
  address: '2405:200:1607:2820:41::36',
  syscall: 'connect',
  code: 'ETIMEDOUT',
  errno: -4039,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.27.2'
    },
    method: 'get',
    url: 'https://raw.githubusercontent.com/EddieHubCommunity/LinkFree/main/config/icons.json',       
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/EddieHubCommunity/LinkFree/main/config/icons.json',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'raw.githubusercontent.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/EddieHubCommunity/LinkFree/main/config/icons.json'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /EddieHubCommunity/LinkFree/main/config/icons.json HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Host: raw.githubusercontent.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/EddieHubCommunity/LinkFree/main/config/icons.json',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'raw.githubusercontent.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://raw.githubusercontent.com/EddieHubCommunity/LinkFree/main/config/icons.json',
    [Symbol(kCapture)]: false
  }
}
√ Add the url of your social media · https://twitter.com/pratik_twt_
W:\LinkFree-CLI\node_modules\enquirer\lib\types\array.js:69
      for (let i = 0; i < items.length; i++) {
                                ^

TypeError: Cannot read properties of undefined (reading 'length')
    at toChoices (W:\LinkFree-CLI\node_modules\enquirer\lib\types\array.js:69:33)
    at SelectPrompt.toChoices (W:\LinkFree-CLI\node_modules\enquirer\lib\types\array.js:80:12)        
    at SelectPrompt.reset (W:\LinkFree-CLI\node_modules\enquirer\lib\types\array.js:34:49)
    at SelectPrompt.initialize (W:\LinkFree-CLI\node_modules\enquirer\lib\types\array.js:25:16)       
    at W:\LinkFree-CLI\node_modules\enquirer\lib\prompt.js:236:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.4.0
```

Am I doing something wrong here?

**Comment by Ananya2001-an** [comment]
Did you create a data folder with your json file in it first?

**Comment by PratikDey** [comment]
> Did you create a data folder with your json file in it first?

Yes, in the root of the project
![image](https://user-images.githubusercontent.com/56970651/221398424-59680912-ac0e-4b70-9c49-929f0263686c.png)

**Comment by Ananya2001-an** [comment]
Wait let me check I think there is some issue with the icons not being able to get displayed

**Comment by Ananya2001-an** [comment]
Hey @PratikDey I just checked everything and it works fine. I think you should try running it again from scratch and make sure that you have all the dependencies installed using `npm install` and also your fork is in sync with the main branch of this repo.

**Comment by Ananya2001-an** [comment]
There seems to be an axios error so that's why the icons are not fetched. Maybe because of some network issues. Just try running it again and I think that should do.

**Comment by PratikDey** [comment]
I am trying again with a new fork and a new clone

**Comment by Pradumnasaraf** [comment]
Yes, 100% an Internet problem. I know this issue. In India, JIO is blocking `raw.githubusercontent.com` host in many places. You can see the error code `443`. 

Can you check if are you able to open this URL https://raw.githubusercontent.com/EddieHubCommunity/LinkFree/main/config/icons.json?

**Comment by Ananya2001-an** [comment]
> Yes, 100% an Internet problem. I know this issue. In India, JIO is blocking `raw.githubusercontent.com` host in many places. You can see the error code `443`. 
> 
> Can you check if are you able to open this URL https://raw.githubusercontent.com/EddieHubCommunity/LinkFree/main/config/icons.json?

I didn't know that. That might create a big problem for many contributors

**Comment by Pradumnasaraf** [comment]
> > Yes, 100% an Internet problem. I know this issue. In India, JIO is blocking `raw.githubusercontent.com` host in many places. You can see the error code `443`.
> > Can you check if are you able to open this URL https://raw.githubusercontent.com/EddieHubCommunity/LinkFree/main/config/icons.json?
> 
> I didn't know that. That might create a big problem for many contributors

Yes, this is an issue for more than a year. It's so painful. I have struggled with Docker a lot in the past.

**Comment by PratikDey** [comment]
> Yes, 100% an Internet problem (more specifically ISP issue). I know this issue. In India, JIO is blocking `raw.githubusercontent.com` host in many places. You can see the error code `443`. You are JIO if I am not wrong
> 
> Can you check if are you able to open this URL https://raw.githubusercontent.com/EddieHubCommunity/LinkFree/main/config/icons.json?

Yes @Pradumnasaraf, I am using Jio Fiber. As you told, this is actually an ISP issue, I am thinking of some way to bypass this

**Comment by Pradumnasaraf** [comment]
> Yes @Pradumnasaraf, I am using Jio Fiber. As you told, this is actually an ISP issue, I am thinking of some way to bypass this

Ah, You can do a couple of things:
- Change the DNS
- Use Gitpod
- Try to use VPN and connect with UK or US region.

**Comment by Pradumnasaraf** [comment]
The sad part is. No one can imagine that this can be an ISP issue and they will keep thinking that there it's a code issue. because almost 99% of people didn't know this ognoing ISP issue :(

**Comment by Ananya2001-an** [comment]
> The sad part is. No one can imagine that this can be an ISP issue and they will keep thinking that there it's a code issue. because more than 99% of people didn't know this ongoing ISP issue :(

Maybe in ReadMe of every open source project they should start adding a section  for Jio users 😂

**Comment by Pradumnasaraf** [comment]
> > The sad part is. No one can imagine that this can be an ISP issue and they will keep thinking that there it's a code issue. because more than 99% of people didn't know this ongoing ISP issue :(
> 
> Maybe in ReadMe of every open source project they should start adding a section for Jio users 😂

Haha. I have something in mind to fix this and remove the `raw.githubusercontent.com` host.

**Comment by Ananya2001-an** [comment]
> > > The sad part is. No one can imagine that this can be an ISP issue and they will keep thinking that there it's a code issue. because more than 99% of people didn't know this ongoing ISP issue :(
> > 
> > Maybe in ReadMe of every open source project they should start adding a section for Jio users 😂
> 
> Haha. I have something in mind to fix this and remove the dependent on the `raw.githubusercontent.com` host.

That would be great 👍

**Comment by Pradumnasaraf** [comment]
Hey, @PratikDey hope you haven't started the development. Can you hold for a bit?

**Comment by PratikDey** [comment]
> Hey, @PratikDey hope you haven't started the development. Can you hold for a bit?

Just started, no worries though
Holding it

**Comment by Pradumnasaraf** [comment]
> `raw.githubusercontent.com` host.

Thank you. I will let you know

**Comment by Ananya2001-an** [comment]
Hey @PratikDey The icons issue is solved now. You can sync your fork with the main branch and try working on the filter now. Feel free to ask for any help 😊
