### ISSUE TITLE
[FEATURE] Adding group and color keys for links

### ISSUE THREAD

**Issue by Ananya2001-an** [Pradumnasaraf/LinkFree-CLI#44]
### Description

**Problem**
Right now we are not allowing users to add group or color keys for their links since they are optional. 

**Potential solution**  
While creating profile we can ask users for the group and color keys if they want to add them or not for that particular link. Also need to do something similar for updating the link in future where we would have to check whether that link has a group or not (same for color key); if it does then giving user the option to update it.  

### Screenshots

![Screenshot 2023-02-24 190724](https://user-images.githubusercontent.com/55504616/221193014-257dc289-be65-47b2-a3c8-07d5e84722e4.jpg)

**Comment by Vyvy-vi** [comment]
I'd like to work on this issue.

**Comment by Ananya2001-an** [comment]
Sure go ahead.

**Comment by Pradumnasaraf** [comment]
> I'd like to work on this issue.

Hey, Vyom. Great to see you see!.

**Comment by Pradumnasaraf** [comment]
Hey, @Vyvy-vi. Are you still working on this issue?

**Comment by Pradumnasaraf** [comment]
This issue is open for getting assigned to new contributors. 🎉

**Comment by Pradumnasaraf** [comment]
> Hi @Pradumnasaraf, if this issue is still open, can I work on this?

Yes, go ahead. If you need help feel free to ask.

**Comment by PratikDey** [comment]
> > Hi @Pradumnasaraf, if this issue is still open, can I work on this?
> 
> Yes, go ahead. If you need help feel free to ask.

Hi @Pradumnasaraf , thanks for assigning me. Can you tell me from where should I get started with?

**Comment by Ananya2001-an** [comment]
Hey @PratikDey you can refer the milestones prompt here: https://github.com/Pradumnasaraf/LinkFree-CLI/blob/main/src/shared/questions/milestones.js 

You can look at the `isGoal` prompt for reference. We want something like that for the group and color keys for links. Feel free to ask if u still have any doubts :)

**Comment by PratikDey** [comment]
So I am writing down my understanding for the issue. We want to have a group key and color key for the links. The color key is already there in `milestone.js` but what about the group key, that part I don't understand
![image](https://user-images.githubusercontent.com/56970651/229335847-f324e9c0-4e46-4964-ac44-6911c28dbaa8.png)

**Comment by Ananya2001-an** [comment]
> So I am writing down my understanding for the issue. We want to have a group key and color key for the links. The color key is already there in `milestones.js` but what about the group key, that part I don't understand

Not milestones in **links** we want to add the group and color keys as prompts. Milestones was just for reference. You have to make changes to the links.js file.

**Comment by PratikDey** [comment]
> > So I am writing down my understanding for the issue. We want to have a group key and color key for the links. The color key is already there in `milestones.js` but what about the group key, that part I don't understand
> 
> Not milestones but in **links** we want to add the group and color keys as prompts. Milestones was just for reference. You have to make changes to the links.js file.

Ok, so the color key I understood. Can you tell me about the group one? Like I want to know if the implementation is going to be the same like the color key implementation.

**Comment by Ananya2001-an** [comment]
It is going to be similar, yes.

**Comment by PratikDey** [comment]
Hi, I added some code.
![image](https://user-images.githubusercontent.com/56970651/229337082-0bb01849-2ff9-434f-9bb5-ebc526083c74.png)
This is the requirement, right?

**Comment by Ananya2001-an** [comment]
Yes

**Comment by Pradumnasaraf** [comment]
Thanks for resolving query @Ananya2001-an

**Comment by Ananya2001-an** [comment]
> Thanks for resolving query that fast @Ananya2001-an

No worries 😄
