### ISSUE TITLE
Fix Issue templates - Add more info in description

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/LinkFree-CLI#68]
Fix Issue templates - Add more info in description

**Comment by yashdev9274** [comment]
Hey @Pradumnasaraf is this issue assigned to anyone yet? and what kind of description you need to add, enlight me I would like to work on it?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf is this issue assigned to anyone yet? and what kind of description you need to add, enlight me I would like to work on it?

Hey,
I just realised the Issue is already been fixed in https://github.com/Pradumnasaraf/LinkFree-CLI/pull/48. Please look for different issues. Thank you.
