### ISSUE TITLE
[OTHER] Choices code optimization

### ISSUE THREAD

**Issue by shoebilyas123** [Pradumnasaraf/LinkFree-CLI#72]
### What would you like to share?

Instead of using whole sentences for switch cases while selecting `choices`. We can store them as  key value pairs and  reference them using constants as:
Example :
`
 const choices = {CH1: "This is a demo choice sentence"};
`
and 
`
case choices.CH1;
`

- [x] I am willing to work on this issue.

**Comment by Pradumnasaraf** [comment]
Hey, @shoebilyas123.

Yes, this can be good, but then the prompt will not work because it looks for an array. 

```js
enquirer
  .prompt([
    {
      type: "select",
      name: "selectedtask",
      choices: choices, // this one
      message: "Choose one option (Press down arrow to traverse the list)",
    },
```

**Comment by shoebilyas123** [comment]
THen I suggest storing the sentences in constants such as CH1 = 'CH1' and then using the constants in the choices array instead of static sentences.

**Comment by Pradumnasaraf** [comment]
I think I will keep the format we have. Because we have only 4-5 choices and it won't do code optimization that much

Thanks for the suggestion. Closing this issue.
