### ISSUE TITLE
[FEATURE] add validation for links

### ISSUE THREAD

**Issue by schmelto** [Pradumnasaraf/LinkFree-CLI#9]
### Description

check whether a link is valid or not

this could be done something like this:
```js
const isValidUrl = urlString => {
  try {
    return Boolean(new URL(urlString));
  } catch (e) {
    return false;
  }
};
```
 https://github.com/Pradumnasaraf/LinkFree-CLI/pull/8#issuecomment-1282996236

**Comment by Nabhag8848** [comment]
Hey @Pradumnasaraf @schmelto, My name is Nabhag. The above validation looks good, but i think we can have one more validation, which will make sure that the input link points to the user profile and the account exist. so lets take an example of github, to look at user profile we have `https://github.com/:username`. Now GET request to URL would either response with status code `200 OK` if the user exist and the user have mention the username correctly else will response with `404 not found` if user not exist or the user have input the wrong username. attaching below example in console for better understanding.

![Screenshot from 2022-11-08 11-38-05](https://user-images.githubusercontent.com/65061890/200887706-6355129d-4564-4271-8d8f-16b6ea9f024f.png)

Now using the same analogy, i have tried using leetcode and this seems to work for the same and seems like would work for all the input urls. 

![Screenshot from 2022-11-08 11-39-31](https://user-images.githubusercontent.com/65061890/200887733-d374fce6-383e-46d1-a173-bc41a4ec3439.png)

### **conclusion**
we can avoid different platform apis to check if the user exist. By making the GET request to the input url. we can let know the user if the input url leads to the correct user profile page if the response status code is 200 OK else let know the user that input url is wrong or the username doesn't exist.

**Comment by Nabhag8848** [comment]
What y'all think about the same? I have some questions too.
## Question 
- making GET request to the website url is expensive?
- will that lead to bad user experience?

**Comment by Pradumnasaraf** [comment]
Hey, 

Sorry for the late reply. Wow really love your point @Nabhag8848. Agree and +1 with the @schmelto opinion.

**Comment by Pradumnasaraf** [comment]
Closing this issue for now. Thanks for opening
